-- seed initial interest categories
insert into interests (name, category) values
  ('hiking', 'outdoor'),
  ('running', 'fitness'),
  ('basketball', 'sports'),
  ('soccer', 'sports'),
  ('volleyball', 'sports'),
  ('tennis', 'sports'),
  ('baseball', 'sports'),
  ('football', 'sports'),
  ('swimming', 'fitness'),
  ('board games', 'games'),
  ('video games', 'games'),
  ('card games', 'games'),
  ('cooking', 'food'),
  ('baking', 'food'),
  ('grilling', 'food'),
  ('wine tasting', 'food'),
  ('coffee', 'social'),
  ('live music', 'entertainment'),
  ('concerts', 'entertainment'),
  ('movies', 'entertainment'),
  ('theater', 'entertainment'),
  ('photography', 'creative'),
  ('art', 'creative'),
  ('painting', 'creative'),
  ('crafts', 'creative'),
  ('reading', 'educational'),
  ('book club', 'educational'),
  ('language exchange', 'educational'),
  ('yoga', 'fitness'),
  ('cycling', 'outdoor'),
  ('fishing', 'outdoor'),
  ('camping', 'outdoor'),
  ('rock climbing', 'outdoor'),
  ('kayaking', 'outdoor'),
  ('dancing', 'social'),
  ('karaoke', 'entertainment'),
  ('trivia', 'games'),
  ('bowling', 'sports'),
  ('golf', 'sports'),
  ('frisbee', 'sports'),
  ('pickleball', 'sports'),
  ('horseshoes', 'games'),
  ('darts', 'games'),
  ('pool', 'games'),
  ('gardening', 'outdoor'),
  ('volunteering', 'social'),
  ('meditation', 'wellness'),
  ('fitness classes', 'fitness'),
  ('martial arts', 'fitness'),
  ('skateboarding', 'sports');
